import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App.jsx'
import './index.css'
import { initViewport } from './lib/viewport'
import { ToastProvider } from './components/ui/primitives'

// Initialize the iOS-robust viewport sizing BEFORE React renders so that
// --app-height / --vvh / safe area vars are already set on <html> when the
// first frame paints. This prevents the initial layout from using a wrong
// window.innerHeight value.
initViewport()

// Register the service worker generated by vite-plugin-pwa.
// Dynamic import so that SSR / non-browser environments don't break.
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      registerSW({ immediate: true })
    })
    .catch(() => {
      // The virtual module only exists when the PWA plugin is active
      // (prod build / dev with devOptions.enabled). Fail silently otherwise.
    })
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <ToastProvider>
        <App />
      </ToastProvider>
    </BrowserRouter>
  </React.StrictMode>
)
