ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "username" TEXT NOT NULL DEFAULT 'Admin';
ALTER TABLE "RoadmapNode" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "RoadmapNode" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'idee';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "ProjectEdge" ADD COLUMN IF NOT EXISTS "sourceHandle" TEXT;
